import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <UserProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
